### ISSUE TITLE
Refactor TiledMapMorph (Outsource API Requests)

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#53]
Problem: Der TiledMapMorph übernimmt Aufgaben der Routenberechnung und der Anfrage an APIs. Normalerweise sollte er aber einfach nur Dinge übergeben bekommen, die er dann zeichnen kann. 

Lösungsidee: 
- SMAWindow initialisiert den Map Morph und setzt eine TiledMapSource (die benötigt der TiledMapMorph weiterhin und kann wahrscheinlich nur schwer ausgelagert werden)
- TiledMapMorph kümmert sich nicht mehr um Anfragen an die RoutingAPI und den Geocoder, diese Aufgaben werden stattdessen vom SMAWindow, SMASearchManager, oder etwas anderem übernommen

Geschätzt: 5

**Comment by TimRiedel** [comment]
## Grobes Prinzip
- `SMAWindow` soll langfristig zu der Core-Klasse werden, während Build-Methoden, verschiedene API Requests und das Setup des TiledMapMorph in separate Klassen ausgelagert werden
- Ein `SearchManager` ist verantwortlich für die Anfragen an APIs und das zurückgeben von Rohdaten in einem Domänenspezifischen Format
<img width="700" alt="image" src="https://user-images.githubusercontent.com/65392679/174858806-5dbccf3c-13bb-4a46-b9bd-232d4261893b.png">

## Designentscheidungen
- Klasse `SearchManager` ist sinnvoll, da die Hauptmethoden für Anfragen an APIs einige Helper Methoden benötigen. Würde man die API Requests auch über die Core Klasse laufen lassen, so würden die Helper Methoden diese nur noch mehr vergrößern und die Core-Klasse könnte leicht wieder zu einer Gott-Klasse ausarten. Insbesondere wenn man daran denkt, dass dort auch Methoden zum API-Key Management, Pin Handling etc. liegen. Zudem fügt `SMAWindow` momentan noch eigenes Verhalten beim Suchen einer Route hinzu (bspw. Error Anzeigen im UI)
- `SearchManager` soll bei einer Routen Anfrage ein komplett konfiguriertes Routen-Objekt zurückgeben. Jedoch benötigt der Tiled Map Morph auch `label` der Start und End Position. Wir haben überlegt im Routen Objekt zusätzlich die beiden `GeocoderResults` zu speichern, haben uns jedoch dagegen entschieden, da dies eine ziemliche Verschachtelung wäre. Die Route hat bereits die meisten Informationen, die der TiledMapMorph benötigt, bis auf die `label` der Start und End Location. Deshalb speichern wir diese nun auf dem Routen Objekt. -> **`Route` und `GeocoderResult` sind somit interne Container zum Speichern von Routen-Suchanfragen bzw. Location-Suchanfragen**. Diese können dann an ein anderes Objekt übergeben werden, welches aus den Informationen Daten für die Anzeige auf dem TiledMapMorph berechnet.
- Nach unseren Refactorings machen `SMAPin` und `SMAGeocoderResult` fast exakt dasselbe. Wir besitzen bereits die `displayLocation` Methode auf dem `MapConfigurator`, die einen Marker für ein `GeocoderResult` anzeigt und dafür eine Bounding Box, LatLong und ein Label benötigt. Die Steps zum Darstellen eines Pins sind mehr oder weniger exakt dieselben, nur dass der Pin bisher noch keine Bounding Box speichert. Stellt man jedoch eine `reverse` Anfrage, also klickt auf die Karte und erwartet einen Pin, der die Location anzeigt, so ist in der zurückgegebenen Json auch eine Bounding Box für den Pin enthalten. Wir könnten also die `displayLocation` Methode nicht nur für das `GeoCoderResult` sondern auch für den `Pin` nutzen. Da dann `SMAPin` und `SMAGeocoderResult` exakt die gleichen Variablen haben, ist es unserer Meinung nach besser, nur eine der Klassen zu benutzen, um Verwirrung bzgl. der Semantik der Klassen zu verhindern. Wir haben uns entschieden `SMAPin` weiterzuverwenden. Damit ist Pin jetzt der Container für Informationen zu einem einzigen Ort und Route der Container für alle Routeninformationen. Sollte der Pin später zusätzliche, für das Window spezifische, Informationen speichern müssen, könnte dafür auch ein Wrapper gebaut werden oder die Informationen werden direkt auf dem Pin gespeichert. Dies wird momentan jedoch nicht benötigt und es macht daher aus unserer Sicht Sinn nur eine einzige Klasse zu haben, die Informationen zu einem Ort speichert.

## TODOs
- [x] Geocoder sollten keine Zoomberechnung beim locaten einer Geokoordinate durchführen, sondern lediglich ein Domänenspezifisches Objekt mit den Rohdaten (in einem bestimmten Format) zurückgeben. Den Zoom auf der Route zu speichern ist aus demselben Grund auch nicht ratsam. Daher muss die Zoomberechnung auf dem `TiledMapMorph` selbst oder auf einem entsprechenden Wrapper erfolgen.
- [x] `centerWorldPos` musste vorerst auf die Route verlegt werden. Später soll die Route jedoch nicht mehr über die Transformation in das world Format Bescheid wissen und nur noch die `centeredLatLong` der Route in Geo Koordinaten zurückgeben.
- [x] Der `SearchManager` zeigt momentan noch ein UI Window an, wenn eine Routenberechnung fehl schlägt. 
- [x] `locate:and:by:` Methode auf dem `SearchManager` umbenennen zu `routeFrom:To:By`
- [x] `getRouteFrom:To:` aus SMAWindow löschen, liegt jetzt in `SMASearchManager`
- [x] BingGeoCoder löschen
- [x] `getZoomFrom:And` auf MapMorph löschen (eventuell Code-Idee von Ole und Leo übernehmen)
- [x] Pin-Selection im SMAWindow refactorn -> placepinlabelledat im TiledMapMorph fällt dadurch weg -> SMAWindow nutzt aktuell noch selber einen Geocoder, sollte durch Aufruf an SearchManager ersetzt werden.

### Misc
- [x] Methode `latLongToWorldPos` vom `SMAMapTileLoader` entfernen und alle Aufrufe durch Aufrufe an `SMAMapConfigurator` ersetzen
- [x] Methode `worldPosToLatLong` vom `SMAMapTileLoader` entfernen und alle Aufrufe durch Aufrufe an `SMAMapConfigurator` ersetzen
- [x] `worldPos` vom "neuen" `Pin` und `Marker` herunterziehen und in den Map Configurator auslagern
- [x] Package `SqueakMaps-APIs` umbenennen in `SqueakMaps-GeoServices`
- [x] Methoden kategorisieren
- [x] Neue Routenrepräsentation auf dem `TiledMapMorph`, die zusätzlich noch die Farbe der Route speichert und somit die Dependency auf das `GeoServices` Package verhindert? Dann könnte das `Window` die Route speichern und beim Anzeigen müsste das in das MapMorph spezifische Objekt umgewandelt werden.
- [x] Doppelklick buggy?

### Tests
- [x] TestORS isApiKeyValid anpassen
- [x] `contentSource` als `JsonUrlReader` zum Geocoder hinzufügen, damit man den Geocoder in Tests mocken kann
- [x] Tests

### Further Refactors
Für weitere wünschenswerte Refactorings einfach mal in die Issues #60, #61 und #62 schauen.

**Comment by LeoKohlenberg** [comment]
## Designentscheidungen

- Wir fanden es sinnvoller das Überprüfen der Gültigkeit des ORS Api-Keys an den verschiedenen Stellen zu streichen und stattdessen den Fehlerfall einfach nur ein mal bei der normalen Anfrage abzufangen. Dadurch spart man sich das Abfangen an allen anderen Stellen und der Nutzer bekommt an genau einer Stelle mit, wenn der Api-Key invalid ist.
- Wir haben uns dazu entschieden eine Klasse `SMAMapConfigurator` zu erstellen, welche die diversen Berechnungen von Zoom, Koordinatenumrechnung etc. übernimmt und am Ende beim `SMATiledMapMorph` einfach nur noch die richtigen Werte konfiguriert und diesen updated.
- Wir löschen den BingGeocoder. Dieser funktioniert nicht und wird zudem nicht verwendet, auch nicht von der BingMapsAPI.

**Comment by TimRiedel** [comment]
## Designentscheidungen
- Nach unseren Refactorings machen `SMAPin` und `SMAGeocoderResult` fast exakt dasselbe. Wir besitzen bereits die `displayLocation` Methode auf dem `MapConfigurator`, die einen Marker für ein `GeocoderResult` anzeigt und dafür eine Bounding Box, LatLong und ein Label benötigt. Die Steps zum Darstellen eines Pins sind mehr oder weniger exakt dieselben, nur dass der Pin bisher noch keine Bounding Box speichert. Stellt man jedoch eine `reverse` Anfrage, also klickt auf die Karte und erwartet einen Pin, der die Location anzeigt, so ist in der zurückgegebenen Json auch eine Bounding Box für den Pin enthalten. Wir könnten also die `displayLocation` Methode nicht nur für das `GeoCoderResult` sondern auch für den `Pin` nutzen. Da dann `SMAPin` und `SMAGeocoderResult` exakt die gleichen Variablen haben, ist es unserer Meinung nach besser, nur eine der Klassen zu benutzen, um Verwirrung bzgl. der Semantik der Klassen zu verhindern. Wir haben uns entschieden `SMAPin` weiterzuverwenden. Damit ist Pin jetzt der Container für Informationen zu einem einzigen Ort und Route der Container für alle Routeninformationen. Sollte der Pin später zusätzliche, für das Window spezifische, Informationen speichern müssen, könnte dafür auch ein Wrapper gebaut werden oder die Informationen werden direkt auf dem Pin gespeichert. Dies wird momentan jedoch nicht benötigt und es macht daher aus unserer Sicht Sinn nur eine einzige Klasse zu haben, die Informationen zu einem Ort speichert.
- Der TiledMapMorph muss eine Route speichern, da er bei jedem zoomen sich neu zeichnet und dafür jedes Mal die Routeninformationen benötigt. Angenommen er würde sie nicht speichern, so müsste er Anfragen an andere Objekte stellen und sich die Informationen von ihnen holen, wofür er wiederrum Referenzen auf diese Objekte haben müsste. Dann ist unserer Meinung nach der `TiledMapMorph` nicht mehr eigenständig.

**Comment by TimRiedel** [comment]
## Designentscheidungen
- Bounding Boxes werden nun als `Rectangle` gespeichert, wobei die zwei angegebenen Ecken die beiden Ecken der Bounding Box sind im Format `links @ unten , rechts @ oben`, wobei die Punkte im Format `Längengrad (E/W) @ Breitengrad (N/S)` gespeichert werden (x @ y).
- Der Geocoder speichert nun auch eine `contentSource` (also einen `JsonUrlReader`) damit man diese Quelle in Tests austauschen und die API mocken kann.
- Wir wollten die Kategorie `SqueakMaps-APIs` in `SqueakMaps-GeoServices` umbenennen. Dort liegen jetzt `RoutingAPI, GeoCoder, Route, Pin`. Das Package beinhaltet nun also Klassen, die für Anfragen von Routen bzw. Locations notwendig sind, wobei sie `Pin` bzw. `Routen` Objekte zurückgeben. Das Umbenennen muss aber über die Command-Line erfolgen und ist noch ein offenes TODO.

**Comment by TimRiedel** [comment]
## Diskussionsbedarf
SMAWindow speichert noch eine Referenz auf den `TiledMapMorph`. Unserer Meinung nach wäre es cool diese Referenz zu entfernen und alles über den `MapConfigurator` laufen zu lassen. Problem daran ist, dass wir für die Distanz- und Zeit-Label der Route Verletzungen des Law-Of-Demeter hätten (z.B. vom Window `self mapConfigurator tiledMapMorhp route getDistance`). Auf der anderen Seite könnte man natürlich argumentieren, dass das `Window` schon seinen Morph speichern kann, der ja ein visuelles Objekt ist, und diesen nur für die Konfiguration an den `MapConfigurator` übergibt. In dem Fall würden sowohl `Window` als auch `MapConfigurator` eine Referenz auf den `TiledMapMorph` speichern (letzteres ist der aktuelle Stand und würde kein refactoring mehr benötigen). Ggf kann man das auch als neues Issue aufnehmen. Was sagt ihr dazu?
