### ISSUE TITLE
Throw more specific errors for failed API Requests

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#60]
As a developer I want to throw specific errors when accessing APIs that show the reason of the failure in order to decide how to handle them and handle them in the `SMAWindow`

**5**

**Comment by TimRiedel** [comment]
Momentan werden noch nicht alle Errors abgefangen, die von verschiedenen Stellen im System geworfen werden. Es wäre erstrebenswert, extra Error-Klassen pro auftretendem Fehler zu haben, sodass dann in der Anwendung entschieden werden kann, wie diese spezifischen Fehler gehandhabt werden. Die TODOs stammen ursprünglich aus dem großen Refactoring:

### Errors
- [x] Spezifische Errors bei der Geocoder `locate` Methode werfen, die das `SMAWindow` abfängt und die Benachrichtigung anzeigt.
- [x] Klasse `SMAInvalidAPIKeyError` erstellen und in `searchMultipleLocations` im `SMAWindow` abfangen und `hasSearched` wieder einbinden
- [x] Spezifische Errors bei der Routenberechnung werfen, die das `SMAWindow` in `searchMultipleLocations` abfängt und die Benachrichtigung anzeigt.
- [x] `Geocoder reverse:withZoom` Error Handling: Beim Doppelklicken auf manche Orte, wie z.b. dem Meer kommt die untenstehende Fehlermeldung auf. Vermutung: wenn keine spezifische Ortsbezeichnung gefunden werden kann, wird ein Undefined Object indiziert.
![image](https://user-images.githubusercontent.com/65392679/178304596-2449c205-4817-44b9-adaf-b4cff823276b.png)
<img width="448" alt="image" src="https://user-images.githubusercontent.com/65392679/178304780-bbe108b3-db6e-43d1-a918-380be82fe90f.png">

**Comment by Durborough** [comment]
Wir führen eine Oberklasse `SMAGeoServiceError` ein. Diese Klasse lebt im `GeoService` Package, damit die Errors mit geshipped werden, wenn die GeoServices ausgeliefert werden.
Von dieser Oberklasse, die generisch alle Fehler handeln soll für die GeoServices, die wir nicht spezifisch abfangen, erben folgende spezielle Error Klassen:

- `InvalidApiKeyError` --> Wird geworfen, wenn der API Key nicht gültig ist.
- `LocationNameNotFoundError` --> Wird geworfen, wenn kein Ort mit dem gesuchten Namen existiert.
- `LocationUnnameableError` --> Wird geworfen, wenn einem Ort keinen Namen zugeordnet werden kann, z.B. Internationalen Gewässern, Bir Tawil Dreieck oder der Antarktis, also Orten die keinem Land zugeordnet sind.
- `RouteTooLongError` --> Wird geworfen, wenn die Route zu lang ist (über 6000km).
- `UnreachableDestinationError` --> Wird geworfen, wenn einer der beiden Punkte nicht von dem anderen erreichbar ist, z.B. z.B. wenn keine Fährverbindung zu einer Insel besteht

**Comment by Durborough** [comment]
`LocationUnnameableError` besitzt speichert das Zoom Level, sowie die angefragten Koordinaten für die kein Name gefunden werden konnte.
Idee für Graceful Fail: Ein Pin wird an die Koordinaten gesetzt. Das Label bekommt die Koordinaten als Inhalt. Die Bounding Box des Pins muss nicht gesetzt werden. Dies liegt daran, da wir die Location nur displayen. Diese Funktionalität benötigt keine Bounding Box, um den Zoom neu zu berechnen.

**Comment by Durborough** [comment]
`LocationNameNotFoundError` speichert den angefragten Namen eines Ortes, zu dem keine Geo Koordinaten gefunden werdn konnten.
Idee für Handling: Hier ist kein Graceful Fail möglich, da wir keine Koordinaten bekommen, mit denen wir arbeiten können. Stattdessen erzeugen wir ein Pop Up Window mit einem Hinweis, dass kein Ort mit dem gesuchten Name gefunden werden konnte.

**Comment by Durborough** [comment]
`SMAInvalidApiKeyError` wird geworfen, wenn 
- der Zugriff auf die API unauthorisiert (Code: 401) erfolgt (z.B. der API Key der gesetzt ist, ist leer)
- der Zugriff auf die API verboten ist (Code: 403) (z.B. der API Key ist ungültig)  
Der Error wird geworfen, wenn der `JsonUrlReader` die jeweiligen Codes bei einer Web response erhält.
Der Error wird im SMA Window abgefangen und ein Promt angezeigt, der sagt, man solle bitte seine API Keys checken.

**Comment by Durborough** [comment]
`SMARouteTooLongError` wird gesignaled bei internem Error Code 2004, der geworfen wird, wenn die zwei Punkte die gesucht werden zu weit auseinander liegen.
Handling: Wird im SMAWindow abgefangen und ein Promt wird angezigt mit dem Hinweis, dass die beiden Punkte zu weit entfernt sind.

**Comment by Durborough** [comment]
`SMAUnreachableDestinationError` bei internem Error Code 2010, der geworfen wird, wenn man von einem Ort nicht zum anderen Ort kommen kann.
Handling: Wird im SMAWindow abgefangen und ein Promt wird angezigt mit dem Hinweis, dass zwischen beiden Punkten keine Route besteht.

**Comment by Durborough** [comment]
**TODO:**

- [x] `on: do: on: do: on: do: on: do: ` implementieren, da wir nicht mehr als 3 Fehler aktuell abfangen können
- [x] testORSisApiKeyValid schlägt fehl, da wir keinen Webclient mocken (wir haben jetzt inkorrekt gemocked indem wir kein JSON zurückgeben, sondern einfach den Fehler signalen)
- [x] "no location with name "textmorph" found" error notification plopped auf beim test laufen lassen? --> `testInvalidLocation` Test ist failure
- [ ] Tests laufen zwei mal durch wenn man sie ausführt und laufen einmal grün und einmal gelb durch???
- [ ] API KEY invalid Fehlerabfangen testen
- [ ] testORSisApiKeyValid ist inkorrekt gemocked indem wir kein JSON zurückgeben, sondern einfach den Fehler signalen, da wir nicht den gesamten webclient mocken wollen

**Comment by Durborough** [comment]
**Error Codes von ORS Routing**
[Link zu Liste](https://giscience.github.io/openrouteservice/documentation/Error-Codes.html#internal-error-codes)
