### ISSUE TITLE
Mock all Legacy API Requests

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swa-teaching/SqueakMaps#62]
As a developer I want to mock all API Requests, so that no test has to make real web requests. This makes the test suite more responsive and less vulnerable to API downtimes or internet connection issues.

**5**

**Comment by TimRiedel** [comment]
### TODO:
- [ ] Entfernen des hard gecodeten OpenRouteService API Key aus der `SMATests` Klasse und der `initialize` Methode.
- [x] RoutingAPITests umbenennen in `SMAOrsRoutingApiTests`
- [x] RoutingAPITets getRouteDuration, getRouteDistance, getBoundingBox spezifischer testen mit direkten Annahmen über Json Objekt
- [x] Geocoder url Erstellung testen

### Laufzeit
Davor:
- `SMATests`: 52 sec
- Alle anderen Kategorien: 2,5 sec

Danach:
- `SMATests`: 
- Alle anderen Kategorien:
